### ISSUE TITLE
move provider specific settings

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-ovirt#11]
see the [amazon settings](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/config/settings.yml) for what can be moved.

until the provider is namespaced under `ovirt` this has to be under the `ems_redhat` key

**Comment by JPrause** [comment]
@agrare do you know if this still a valid issue? If yes, let me know and I'll remove the stale label. If not I can close. If there's no update by next week, I'll be closing this issue.

**Comment by agrare** [comment]
I don't see any worker settings in core, @borod108 can you see if any RHV events are still defined in core?  If not you can close this issue.
