### ISSUE TITLE
Allow linking from ManageIQ UI to oVirt admin UI for the given Infra Provider

### ISSUE THREAD

**Issue by vojtechszocs** [ManageIQ/manageiq-providers-ovirt#139]
![admin_ui_toolbar_button](https://user-images.githubusercontent.com/648971/32623649-2c2f2e5e-c587-11e7-8f9e-97e7ba601e35.png)

- [x] [Add ems_infra_admin_ui feature](https://github.com/ManageIQ/manageiq/pull/16403)
- [x] [Add ems_infra_admin_ui feature support](https://github.com/ManageIQ/manageiq-ui-classic/pull/2644)
- [x] [Add admin_ui feature support to InfraManager](https://github.com/ManageIQ/manageiq-providers-ovirt/pull/133)
- [x] [Update ems_infra_admin_ui feature to role assignment](https://github.com/ManageIQ/manageiq/pull/16484)
- [x] [Update Engine version check for admin_ui feature](https://github.com/ManageIQ/manageiq-providers-ovirt/pull/148)
- [ ] Resolve open issues:
 - use [Net::HTTP](https://apidock.com/ruby/Net/HTTP) instead of `OvirtSDK4::HttpClient` (or `raw_connect` from `ApiIntegration`?)
 - ~~should we check for supported Engine version when defining `admin_ui` support in `InfraManager`?~~

**Comment by vojtechszocs** [comment]
cc @jhernand @oourfali

**Comment by vojtechszocs** [comment]
> should we check for supported Engine version when defining admin_ui support in InfraManager?

For now, we can enable `admin_ui` feature support when Engine version >= 4.2

Once [Ravi's patch](https://gerrit.ovirt.org/#/c/82997/) gets backported to 4.1.z we can update that condition.

**Comment by oourfali** [comment]
@vojtechszocs Ravi's patch is merged. Will be part of 4.1.8.

**Comment by vojtechszocs** [comment]
> @vojtechszocs Ravi's patch is merged. Will be part of 4.1.8.

Thanks, I'll submit new PR to make `admin_ui` feature support enabled when Engine version >= 4.1.8

**Comment by vojtechszocs** [comment]
> Thanks, I'll submit new PR to make `admin_ui` feature support enabled when Engine version >= 4.1.8

PR submitted, link in task checklist above.

**Comment by vojtechszocs** [comment]
The relevant changes landed in ManageIQ 6.0 and were also backported to 5.9 (Gaprindashvili). This feature now works with oVirt 4.1.8 and above.

Should we close this RFE? (The only remaining issue is a technical one and not essential, could be addressed now or later.)

cc @jelkosz

**Comment by mfeifer** [comment]
closed as completed
