### ISSUE TITLE
Request to set the maintenance flag

### ISSUE THREAD

**Issue by syncrou** [ManageIQ/manageiq-providers-ovirt#141]
The Provisioning dialog 'Environment' tab now shows current maintenance status per provider.  
Per this comment from @agrare - https://github.com/ManageIQ/manageiq/pull/16464#issuecomment-344099487
we would like to see this flag tracked with ovirt providers moving forward.

https://bugzilla.redhat.com/show_bug.cgi?id=1513413

**Comment by masayag** [comment]
Fixed by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/147
