### ISSUE TITLE
move ovirt specific events

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-ovirt#16]
similar to moving the settings we can also move event names (see [amazon](https://github.com/ManageIQ/manageiq-providers-amazon/pull/163/files) for an example)

**Comment by JPrause** [comment]
@agrare would you know if is this still a valid issue? If yes, let me know and I'll remove the stale label. If not I can close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
