### ISSUE TITLE
Add specific handeling for exceptions from the OvirtSDK

### ISSUE THREAD

**Issue by borod108** [ManageIQ/manageiq-providers-ovirt#17]
As per https://github.com/ManageIQ/manageiq-providers-ovirt/pull/2#discussion_r113063956
When the OvirtSDK will have specific exceptions they should be handled accordingly.

Please see also:
https://bugzilla.redhat.com/show_bug.cgi?id=1443420

**Comment by JPrause** [comment]
@borod108 is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
