### ISSUE TITLE
GeneralUpdateMethodNamesDecorator should implement respond_to_missing?

### ISSUE THREAD

**Issue by borod108** [ManageIQ/manageiq-providers-ovirt#18]
As per https://github.com/ManageIQ/manageiq-providers-ovirt/pull/2#discussion_r113064088
The GeneralUpdateMethodNamesDecorator should implement respond_to_missing? to do that we need to implement it in the ovirt-gem.

**Comment by JPrause** [comment]
@borod108 is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
