### ISSUE TITLE
miq provider api to ovirt 4.2.0  is outdated

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-ovirt#181]
Please update the version 3.0 to 4.0 as state in following message.

* message from ovirt-4.2.0 dashboard. 10.10.184.21 is from miq fine-4 and master branch of miq instances.
```
Client from address "10.10.184.21" is using version 3 of the API, which has been deprecated since version 4.0 of the engine, and will no longer be supported starting with version 4.3. Make sure to update that client to use a supported versions of the API and the SDKs, before upgrading to version 4.3 of the engine.
```
![image](https://user-images.githubusercontent.com/378638/34268078-01573f44-e645-11e7-8e61-40e57494aa3b.png)

**Comment by masayag** [comment]
@tjyang 

The message is due to the fact the that  manageiq-providers-ovirt/config/settings.yml isn't configured to work with v4 of ovirt-engine api. In order to enable it you should change the file to `:use_ovirt_engine_sdk: true`

**Comment by tjyang** [comment]
@masayag 
As shown in this [ems_redhat setting screenshot](https://user-images.githubusercontent.com/378638/34295995-ea7dd544-e6d5-11e7-9b30-a254386955a5.png) taken from miq running from master branch, the "use_ovirt_engine_sdk" is already set to true by default and it  triggered the warning message on ovrt 4.2.0 side.
Also when I added in ovirt-4.2.0 as provider, I don't have option of adding ovirt but R.H. Virtualization option, assuming this ok for ovirt.

**Comment by masayag** [comment]
@tjyang according to your first message, the client which accessed ovirt-engine is '10.10.184.2'1 is from miq fine-4' - 
The default of `user_ovirt_engine_sdk` was set to `true` by https://github.com/ManageIQ/manageiq-providers-ovirt/commit/ff844433e31851c0aba68e6b8840ad3542cfa642

AFAIK, it wasn't backported to FINE. Could you check the value of that properly on 10.10.184.2 ?

Regarding the second comment, in the providers selection 'Red Hat Virtualization' represents 'ovirt-engine' as well.

**Comment by tjyang** [comment]
@masayag , you are right about fine-4 miq(10.10.184.2) , the default  is [" :use_ovirt_engine_sdk: false"](https://user-images.githubusercontent.com/378638/34298804-26db69ca-e6e5-11e7-83d8-777393e5185f.png)
* Regarding the second comment, in the providers selection 'Red Hat Virtualization' represents 'ovirt-engine' as well.
  * Do you know if there is a plan to have ovirt has it's own icon and provider name ?

**Comment by oourfali** [comment]
No plan for that at the moment.

**Comment by oourfali** [comment]
Does it work well when changing it to true?
As @masayag metioned, it is true by default in 'gaprindashvili'

**Comment by tjyang** [comment]
@oourfali , See the [log on ovirt-4.2.0](https://user-images.githubusercontent.com/378638/34300189-96b90778-e6ec-11e7-87ab-3e33a945dfb7.png), miq fine-4(*.182.21) still trigger the warning message after I set the value to true in advance setting. 
 
I will do another test to see if newer version of miq (Gapri+) will trigger warning message.

**Comment by JPrause** [comment]
@tjyang is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
