### ISSUE TITLE
[RFE] Add SSH credentials to the oVirt Manager

### ISSUE THREAD

**Issue by fdupont-redhat** [ManageIQ/manageiq-providers-ovirt#229]
oVirt is adding roles and playbooks to the oVirt Manager as a way to extend operations. Not all of them are available through the API (yet?). It would be great to add SSH credentials to the oVirt Manager, in order to run these extra playbooks on the oVirt Manager, as it has password-less credentials to the whole oVirt infrastructure.

The first use case is to leverage the oVirt.v2v-conversion-host role (https://github.com/oVirt/ovirt-ansible-v2v-conversion-host) from ManageIQ, from within the V2V plugin. We could enable/disable the role from custom (naitve?) buttons, by connecting to the oVirt Manager and running the corresponding playbooks.

Further, this would allow for quick prototyping of new actions in the oVirt environment by creating roles and playbooks. Once the action and its interface (inputs and outputs) is stable, it can be exposed through the oVirt API.

Ideally, the credentials type is SSH keys, as it works better with ProxyCommand or ProxyJump options.

**Comment by fdupont-redhat** [comment]
@mwperina Opened the associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1561353

**Comment by bthurber** [comment]
@blomquisg checking on status for this as it is a piece we need to help automate the configuration of the RHV conversion hosts.

**Comment by blomquisg** [comment]
@borod108 I don't see any progress reported in the bug (which is still in "new" status).  Is this currently underway?  Or, not yet started?

**Comment by borod108** [comment]
Its in progress.

**Comment by borod108** [comment]
resolved by https://github.com/ManageIQ/manageiq-ui-classic/pull/3983
