### ISSUE TITLE
Rhev refresh failes

### ISSUE THREAD

**Issue by LubaLimon** [ManageIQ/manageiq-providers-ovirt#278]
I'm using latest gaprindashvili version of manageiq-providers-ovirt and all refresh requests are failing with following error

`ERROR -- : /root/icdc/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:9:in `refresh'
/root/icdc/manageiq/app/models/ems_refresh.rb:97:in `block in refresh'
/root/icdc/manageiq/app/models/ems_refresh.rb:96:in `each'
/root/icdc/manageiq/app/models/ems_refresh.rb:96:in `refresh'
/root/icdc/manageiq/app/models/miq_queue.rb:449:in `block in dispatch_method'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/root/icdc/manageiq/app/models/miq_queue.rb:448:in `dispatch_method'
/root/icdc/manageiq/app/models/miq_queue.rb:425:in `block in deliver'
/root/icdc/manageiq/app/models/user.rb:332:in `with_user_group'
/root/icdc/manageiq/app/models/miq_queue.rb:425:in `deliver'`

**Comment by masayag** [comment]
@LubaLimon could you attach the evm.log that contains the refresh error ?

**Comment by mfeifer** [comment]
Please re-open if this is still a bug.
