### ISSUE TITLE
Avoid parsing the descriptions of events

### ISSUE THREAD

**Issue by jhernand** [ManageIQ/manageiq-providers-ovirt#45]
Currently the oVirt provider parses the descriptions of events in order to extract details like the virtual machine name. For example, from the `parse_target_name` method inside the [`event_parser.rb`](https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/event_parser.rb) file:

```ruby
def self.parse_target_name(message, event_type)
    case event_type
    when "NETWORK_ADD_VM_INTERFACE"
      # sample message: "Interface nic1 (VirtIO) was added to VM v5. (User: admin@internal-authz)"
      message.split(/\s/)[7][0...-1]
    when "NETWORK_INTERFACE_PLUGGED_INTO_VM"
      # sample message: "Network Interface nic1 (VirtIO) was plugged to VM v5. (User: admin@internal)"
      message.split(/\s/)[8][0...-1]
    else
      # sample message: "VM v5 was created by admin@internal."
      message.split(/\s/)[1]
    end
end
```

This is very fragile, as the description of the event may change at any point without notice. For the specific events that this code is handling it is better to follow the `<vm .../>` link that is included in the event, and extract the virtual machine name from there:

```xml
  <event href="/ovirt-engine/api/events/99" id="99">
    <description>Interface nic2 (VirtIO) was added to VM myvm. (User: admin@internal-authz)</description>
    <code>932</code>
    ...
    <vm href="/ovirt-engine/api/vms/34bc8a23-8749-481c-a67e-dd855960cf79" id="34bc8a23-8749-481c-a67e-dd855960cf79"/>
    ...
  </event>
```

Using the Ruby SDK this could be done with the following code:

```ruby
event = ...
vm = connection.follow_link(event.vm)
vm_name = vm.name
```

**Comment by borod108** [comment]
If I remember correctly the reason it was done this way was because we do not know if when the event will be handled the vm  will exist.
Not sure if its worth the fragile structure but that was a consideration.

**Comment by pkliczewski** [comment]
The vm could be removed from the provider as well as from the db. We need to provide the name for a vm due to the way how `save_inventory` works.

We can reduce the need to run this code by following the link but if vm was removed we can check the db. There could be situation when vm was removed from the db as well so this fragile parsing needs to be used.

**Comment by pkliczewski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve event parsing for refresh for new target](https://trello.com/c/L9rtqKGw/140-improve-event-parsing-for-refresh-for-new-target)

**Comment by jhernand** [comment]
For cases when the VM link doesn't exist we should, in the future, use the mechanism that will be added if/when this oVirt RFE is implemented:

  [RFE] Add properties to events
  https://bugzilla.redhat.com/1456711

**Comment by JPrause** [comment]
@jhernand is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
