### ISSUE TITLE
[RFE] Allow vm reconfigure to edit network interface controllers

### ISSUE THREAD

**Issue by gpavinteractiv** [ManageIQ/manageiq-providers-ovirt#461]
Essentially, request to be able to add / remove / modify network interfaces in the reconfigure section of ovirt vms, as has been done for vmware provider

See https://bugzilla.redhat.com/show_bug.cgi?id=1749835 for a RFE found on bugzilla that should also apply to ovirt provider additionally to vmware

**Comment by gekorob** [comment]
Hi @gpavinteractiv, we are already working on it. I think It sgoukd not take too much time.

**Comment by gekorob** [comment]
Closing 'cause solved by #480, #478, #477
