### ISSUE TITLE
[RFE] Allow vm reconfigure to resize ovirt vm disks

### ISSUE THREAD

**Issue by gpavinteractiv** [ManageIQ/manageiq-providers-ovirt#469]
It should be possible to resize ovirt vm disks from the reconfigure menu
edit : just found this : https://bugzilla.redhat.com/show_bug.cgi?id=1671330

**Comment by gekorob** [comment]
Hi @gpavinteractiv, sorry for the delay. I think that if you can contribute developing this enhancement there will be no problem. If you need anything just ask.

**Comment by gpavinteractiv** [comment]
Sorry, I do not have the skill to implement it from scratch myself.
The feature to edit NIC for oVirt/RHV vm is said to be coming soon. So I guess I could then look at that implementation in order to get some ideas for where to start.

**Comment by gekorob** [comment]
Closing 'cause solved by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/483
