### ISSUE TITLE
Missing asynchronous context-free credential validation for DDF

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-ovirt#508]
There's no `self.verify_credentials` for the add provider form, also the already existing validation operates with DB models, so it's basically the same problem as in https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/387 but here for the default and the metrics endpoint.

@miq-bot assign @agrare 
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818

**Comment by agrare** [comment]
Hey @skateman actually there is one it is just in [`InfraManager::ApiIntegrations`](https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/api_integration.rb#L209-L233).  I had to update it to match what you have in https://github.com/ManageIQ/manageiq-providers-ovirt/pull/509 so I'll push the changes to your branch but verification and adding the provider works, going to close this
