### ISSUE TITLE
Validating credentials when adding a provider always passes

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-ovirt#526]
When trying to add a provider with invalid credentials (even a nonexisting host) it always passes...

@miq-bot add_label bug
@miq-bot assign @agrare

**Comment by skateman** [comment]
cc @mzazrivec

**Comment by mzazrivec** [comment]
@agrare this one can be closed.

**Comment by mzazrivec** [comment]
Actually, I spoke too soon. I mistakenly thought https://github.com/ManageIQ/manageiq-providers-ovirt/pull/525 would fix this issue, but it did not. The problem described above is still present and needs to be addressed in backend.

**Comment by zigaSRC** [comment]
@mzazrivec @agrare This bug is still present in lasker-1. 

Furthermore, authentication for metrics collection for ovirt provider is no longer working. Manageiq no longer collects the metrics in lasker-1. Collection/authentication worked in jansa-2. 

```
[----] W, [2021-09-07T09:52:32.674478 #2502:2ad348893960]  WARN -- evm: MIQ(ManageIQ::Providers::Redhat::InfraManager#authentication_che
ck_no_validation) type: [:metrics] for [6] [srcOLVM] Validation failed: invalid, undefined method `async_exec' for nil:NilClass
[----] W, [2021-09-07T09:52:32.674650 #2502:2ad348893960]  WARN -- evm: MIQ(AuthUseridPassword#validation_failed) [ExtManagementSystem]
[6], previously valid on: 2021-07-21 09:15:25 UTC, previous status: [Invalid]
```
