### ISSUE TITLE
Error "path conflicts with opaque" while setting up RHEV/oVirt Metrics connection 

### ISSUE THREAD

**Issue by sgarrard** [ManageIQ/manageiq-providers-ovirt#550]
Howdy! I am standing up a brand new instance of ManageIQ Kasparov and attempting to connect it to a brand new instance of oVirt 4.4.4.7-1.el8. I can create and connect the infrastructure provider to oVirt and see the clusters, VMs, etc., but when I try to enable the Metrics part, it fails with the error “Validation failed: path conflicts with opaque”

![Screen Shot 2021-03-02 at 5 22 34 PM](https://user-images.githubusercontent.com/80008757/109876865-e7447180-7c37-11eb-82eb-0ad0577ad567.png)

I followed the ManageIQ documentation for creating a DWH user for ManageIQ and granting it the appropriate permissions in the Postgres database, and I can connect to the database using those credentials from my ManageIQ server, so I know the firewall and credentials are correct. I’m at a loss for what could be wrong except for a version mismatch between the version of oVirt I installed and what’s supported by ManageIQ…

![image](https://user-images.githubusercontent.com/80008757/109877201-528e4380-7c38-11eb-821d-99b2cc2773f8.png)

evm.log excerpt:
[evm.log](https://github.com/ManageIQ/manageiq-providers-ovirt/files/6079445/evm.log)

rhevm.log excerpt:
[rhevm.log](https://github.com/ManageIQ/manageiq-providers-ovirt/files/6079446/rhevm.log)

Appreciate the support!
Stefan

**Comment by agrare** [comment]
Thanks for the bug report @sgarrard!  I was able to reproduce this, the issue is the ovirt backend code is expecting that the "main" API credentials will always be sent for verify_credentials but more recent versions of the UI split the credentials up into different tabs with their own verification.

It is actually the default credential check that is throwing that exception without even making it to the metrics check.

**Comment by sgarrard** [comment]
Thank you @agrare for the quick turnaround on this one! Is there an easy way for me to pull this change before the next major release? I'm not a developer and it's a bit of a mystery to me.

**Comment by agrare** [comment]
@sgarrard definitely, if you want to manually apply the patch you can ssh to your appliance and edit this file: `vi $(bundle show manageiq-providers-ovirt)/app/models/manageiq/providers/redhat/infra_manager/api_integration.rb` and add this line https://github.com/ManageIQ/manageiq-providers-ovirt/pull/551/files#diff-e275a9678ece17256de11e64463619843136b35ff28ec827c8f571d0c418f5feR294 to the `check_connect_api` method, then `systemctl restart evmserverd`

**Comment by sgarrard** [comment]
Thank you, that worked perfectly! Again, I greatly appreciate the help squashing this bug!

Stefan

________________________________
