### ISSUE TITLE
Remove ovirt inventory code from manageiq-gems-pending

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-ovirt#8]
Now that the oVirt provider has its own repo, it's time to move the ovirt specific code from manageiq-gems-pending to here. See https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending/ovirt_provider.

**Comment by jhernand** [comment]
@miq-bot assign @jhernand

**Comment by bdunne** [comment]
Both PR's are merged, so I closed the issue
