### ISSUE TITLE
Both CNAME and Aname of rhev provider is shown in RHEV host summary page 

### ISSUE THREAD

**Issue by sshveta** [ManageIQ/manageiq-providers-ovirt#93]
our RHV provider is configured using this A name - cfme-smicro-628-a05.cfme2.lab.eng.rdu2.redhat.com 
and in the CFME UI it actually shows the host item with its CNAME - env-rhv41-01.cfme2.lab.eng.rdu2.redhat.com - but on the details page for that host, the A name is used for the 'hostname' field.

Also , In Service catalogs , the CNAME of the host is displayed .

Can we show one hostname at all places ?

![screenshot from 2017-09-07 08 58 40](https://user-images.githubusercontent.com/3866976/30174273-53a84966-93af-11e7-8556-b193b5148344.png)

**Comment by sshveta** [comment]
![screenshot from 2017-09-07 09 00 03](https://user-images.githubusercontent.com/3866976/30174284-5e2623b8-93af-11e7-9a6d-d1a661040de5.png)

**Comment by JPrause** [comment]
@sshveta is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
